// <auto-generated />
using System;
using Final_project___MaxFitness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_project___MaxFitness.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220121309_FirstTest")]
    partial class FirstTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Final_project___MaxFitness.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroup = "chest",
                            Name = "Bench Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroup = "chest",
                            Name = "Incline Dumbbell Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroup = "chest",
                            Name = "Cable Flyes",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroup = "chest",
                            Name = "Push-Ups",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroup = "chest",
                            Name = "Dumbbell Pullover",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroup = "back",
                            Name = "Deadlift",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 7,
                            MuscleGroup = "back",
                            Name = "Lat Pulldown",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 8,
                            MuscleGroup = "back",
                            Name = "Barbell Row",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 9,
                            MuscleGroup = "back",
                            Name = "Seated Cable Row",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 10,
                            MuscleGroup = "back",
                            Name = "Face Pulls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 11,
                            MuscleGroup = "shoulders",
                            Name = "Overhead Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 12,
                            MuscleGroup = "shoulders",
                            Name = "Lateral Raises",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 13,
                            MuscleGroup = "shoulders",
                            Name = "Front Raises",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 14,
                            MuscleGroup = "shoulders",
                            Name = "Reverse Flyes",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 15,
                            MuscleGroup = "shoulders",
                            Name = "Arnold Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 16,
                            MuscleGroup = "biceps",
                            Name = "Barbell Curl",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 17,
                            MuscleGroup = "biceps",
                            Name = "Hammer Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 18,
                            MuscleGroup = "biceps",
                            Name = "Incline Dumbbell Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 19,
                            MuscleGroup = "biceps",
                            Name = "Preacher Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 20,
                            MuscleGroup = "biceps",
                            Name = "Cable Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 21,
                            MuscleGroup = "triceps",
                            Name = "Tricep Dips",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 22,
                            MuscleGroup = "triceps",
                            Name = "Skull Crushers",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 23,
                            MuscleGroup = "triceps",
                            Name = "Tricep Pushdown",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 24,
                            MuscleGroup = "triceps",
                            Name = "Overhead Tricep Extension",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 25,
                            MuscleGroup = "triceps",
                            Name = "Close-Grip Bench Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 26,
                            MuscleGroup = "legs",
                            Name = "Barbell Squat",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 27,
                            MuscleGroup = "legs",
                            Name = "Romanian Deadlift",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 28,
                            MuscleGroup = "legs",
                            Name = "Leg Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 29,
                            MuscleGroup = "legs",
                            Name = "Leg Curl",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 30,
                            MuscleGroup = "legs",
                            Name = "Calf Raises",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 31,
                            MuscleGroup = "legs",
                            Name = "Bulgarian Split Squat",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 32,
                            MuscleGroup = "abs",
                            Name = "Crunches",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 33,
                            MuscleGroup = "abs",
                            Name = "Hanging Leg Raises",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 34,
                            MuscleGroup = "abs",
                            Name = "Plank",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 35,
                            MuscleGroup = "abs",
                            Name = "Cable Woodchops",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 36,
                            MuscleGroup = "abs",
                            Name = "Ab Wheel Rollout",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 37,
                            MuscleGroup = "forearms",
                            Name = "Wrist Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 38,
                            MuscleGroup = "forearms",
                            Name = "Reverse Wrist Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 39,
                            MuscleGroup = "forearms",
                            Name = "Farmer's Walk",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 40,
                            MuscleGroup = "forearms",
                            Name = "Plate Pinch",
                            Type = "Isolation"
                        });
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalReps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutExerciseLogs");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntensityScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutExerciseLog", b =>
                {
                    b.HasOne("Final_project___MaxFitness.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
