// <auto-generated />
using System;
using Final_project___MaxFitness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_project___MaxFitness.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429195903_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_project___MaxFitness.Models.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("int");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#e63946",
                            Description = "Complete a squat variation every day for 30 days. Start with bodyweight and progressively add weight. Build insane leg strength and discipline.",
                            Difficulty = "Intermediate",
                            DurationDays = 30,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "fa-person-running",
                            Name = "30-Day Squat Challenge",
                            ParticipantCount = 0,
                            Rules = "Do at least one set of squats every day;Minimum 10 reps per set;Rest days allowed but must make up the next day;Log every session in MaxFitness",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Color = "#ff6b35",
                            Description = "Hit 5,000 steps minimum every single day. A simple but powerful habit that keeps you moving even on rest days. Perfect for active recovery.",
                            Difficulty = "Beginner",
                            DurationDays = 30,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "fa-shoe-prints",
                            Name = "5K Steps Daily",
                            ParticipantCount = 0,
                            Rules = "Walk at least 5,000 steps every day;Track with any step counter or fitness watch;Post your daily count in the community;Miss a day and you're out",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ffd166",
                            Description = "Train every single day for 7 days straight. Mix up muscle groups, intensity, and workout types. Test your mental and physical limits.",
                            Difficulty = "Advanced",
                            DurationDays = 7,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "fa-fire",
                            Name = "No Rest Day Week",
                            ParticipantCount = 0,
                            Rules = "Work out every day for 7 consecutive days;Each session must be at least 30 minutes;Vary muscle groups to prevent overtraining;Log all sessions in MaxFitness",
                            StartDate = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Color = "#22c55e",
                            Description = "Work your way up to 100 push-ups in a single session. Start wherever you are and build up over 4 weeks. Upper body gains guaranteed.",
                            Difficulty = "Intermediate",
                            DurationDays = 28,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "fa-hand-fist",
                            Name = "Push-Up Master",
                            ParticipantCount = 0,
                            Rules = "Do push-ups at least 5 days per week;Track your max set each session;Goal is 100 push-ups in one session by day 28;Any push-up variation counts",
                            StartDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Color = "#8b5cf6",
                            Description = "Maintain a 14-day consecutive workout streak. No excuses, no skipping. Build the habit that separates the dedicated from the rest.",
                            Difficulty = "Advanced",
                            DurationDays = 14,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "fa-link",
                            Name = "Iron Streak",
                            ParticipantCount = 0,
                            Rules = "Work out every day for 14 days;Minimum 20 minutes per session;Any workout type counts;Log in MaxFitness to track your streak",
                            StartDate = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.ChallengeParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("ChallengeParticipants");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.CommunityPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Comments")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgressSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("CommunityPosts");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroup = "chest",
                            Name = "Bench Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroup = "chest",
                            Name = "Incline Dumbbell Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroup = "chest",
                            Name = "Cable Flyes",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroup = "chest",
                            Name = "Push-Ups",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroup = "chest",
                            Name = "Dumbbell Pullover",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroup = "back",
                            Name = "Deadlift",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 7,
                            MuscleGroup = "back",
                            Name = "Lat Pulldown",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 8,
                            MuscleGroup = "back",
                            Name = "Barbell Row",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 9,
                            MuscleGroup = "back",
                            Name = "Seated Cable Row",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 10,
                            MuscleGroup = "back",
                            Name = "Face Pulls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 11,
                            MuscleGroup = "shoulders",
                            Name = "Overhead Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 12,
                            MuscleGroup = "shoulders",
                            Name = "Lateral Raises",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 13,
                            MuscleGroup = "shoulders",
                            Name = "Front Raises",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 14,
                            MuscleGroup = "shoulders",
                            Name = "Reverse Flyes",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 15,
                            MuscleGroup = "shoulders",
                            Name = "Arnold Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 16,
                            MuscleGroup = "biceps",
                            Name = "Barbell Curl",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 17,
                            MuscleGroup = "biceps",
                            Name = "Hammer Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 18,
                            MuscleGroup = "biceps",
                            Name = "Incline Dumbbell Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 19,
                            MuscleGroup = "biceps",
                            Name = "Preacher Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 20,
                            MuscleGroup = "biceps",
                            Name = "Cable Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 21,
                            MuscleGroup = "triceps",
                            Name = "Tricep Dips",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 22,
                            MuscleGroup = "triceps",
                            Name = "Skull Crushers",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 23,
                            MuscleGroup = "triceps",
                            Name = "Tricep Pushdown",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 24,
                            MuscleGroup = "triceps",
                            Name = "Overhead Tricep Extension",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 25,
                            MuscleGroup = "triceps",
                            Name = "Close-Grip Bench Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 26,
                            MuscleGroup = "legs",
                            Name = "Barbell Squat",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 27,
                            MuscleGroup = "legs",
                            Name = "Romanian Deadlift",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 28,
                            MuscleGroup = "legs",
                            Name = "Leg Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 29,
                            MuscleGroup = "legs",
                            Name = "Leg Curl",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 30,
                            MuscleGroup = "legs",
                            Name = "Calf Raises",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 31,
                            MuscleGroup = "legs",
                            Name = "Bulgarian Split Squat",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 32,
                            MuscleGroup = "abs",
                            Name = "Crunches",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 33,
                            MuscleGroup = "abs",
                            Name = "Hanging Leg Raises",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 34,
                            MuscleGroup = "abs",
                            Name = "Plank",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 35,
                            MuscleGroup = "abs",
                            Name = "Cable Woodchops",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 36,
                            MuscleGroup = "abs",
                            Name = "Ab Wheel Rollout",
                            Type = "Bodyweight"
                        },
                        new
                        {
                            Id = 37,
                            MuscleGroup = "forearms",
                            Name = "Wrist Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 38,
                            MuscleGroup = "forearms",
                            Name = "Reverse Wrist Curls",
                            Type = "Isolation"
                        },
                        new
                        {
                            Id = 39,
                            MuscleGroup = "forearms",
                            Name = "Farmer's Walk",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 40,
                            MuscleGroup = "forearms",
                            Name = "Plate Pinch",
                            Type = "Isolation"
                        });
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.PostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetCount")
                        .HasColumnType("int");

                    b.Property<string>("SetsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalReps")
                        .HasColumnType("int");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("float");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutExerciseLogs");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("IntensityScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalReps")
                        .HasColumnType("int");

                    b.Property<int>("TotalSets")
                        .HasColumnType("int");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.ChallengeParticipant", b =>
                {
                    b.HasOne("Final_project___MaxFitness.Models.Challenge", "Challenge")
                        .WithMany("Participants")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.CommunityPost", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Final_project___MaxFitness.Models.WorkoutSession", "WorkoutSession")
                        .WithMany()
                        .HasForeignKey("WorkoutSessionId");

                    b.Navigation("User");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.PostComment", b =>
                {
                    b.HasOne("Final_project___MaxFitness.Models.CommunityPost", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.PostLike", b =>
                {
                    b.HasOne("Final_project___MaxFitness.Models.CommunityPost", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutExerciseLog", b =>
                {
                    b.HasOne("Final_project___MaxFitness.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutSession", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.Challenge", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Final_project___MaxFitness.Models.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
